//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeroMerch.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseKey
    {
        public int Id { get; set; }
        public bool WasUsed { get; set; }
        public int LicenseKey1 { get; set; }
        public Nullable<int> OrderLine_Id { get; set; }
        public string KeyString { get; set; }
    
        public virtual OrderLine OrderLine { get; set; }
    }
}
