//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeroMerch.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderContent
    {
        public Nullable<int> KeyId { get; set; }
        public int OrderId { get; set; }
        public string Manufacturer { get; set; }
        public string ProductName { get; set; }
        public decimal NetUnitPrice { get; set; }
        public string KeyString { get; set; }
        public bool WasUsed { get; set; }
    }
}
